package com.fluxyBackend.invoicing.enums;

/** Historial de un comprobante. */
public enum DocumentEventType {
    CREATED, SENT_TO_PROVIDER, ACCEPTED, REJECTED, ERROR, RETRY_SCHEDULED, STATUS_CHECKED, WEBHOOK_RECEIVED,
    EMAIL_SENT, EMAIL_FAILED, EMAIL_RESENT, CREDIT_NOTE_CREATED, CANCEL_PENDING, CANCELLED, CANCEL_REVERTED,
    PUBLIC_LINK_REVOKED, MANUAL_RETRY
}
