spring.application.name=fluxy-backend
spring.datasource.url=jdbc:postgresql://localhost:5432/fluxy_db
spring.datasource.username=postgres
spring.datasource.password=Moreno07
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
server.port=8080
jwt.secret=VGhpc0lzQVN1cGVyU2VjcmV0S2V5Rm9yRmx1eHlKV1QyMDI2MTIzNDU2Nzg5
jwt.expiration=86400000

# Email

sendgrid.api.key=${SENDGRID_API_KEY}
mail.from=${MAIL_FROM}