package com.fluxyBackend.customer.activity;

public enum CustomerActivityType {
    CUSTOMER_CREATED, CUSTOMER_UPDATED, ORDER_CREATED, ORDER_PAID, ORDER_DELIVERED, ORDER_CANCELLED,
    TAG_ADDED, TAG_REMOVED, NOTE_CREATED, COUPON_USED, CAMPAIGN_INTERACTION, REFUND_CREATED
}
